import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"; // Corrected import
import "./globals.css";

// Configure DM Sans font
const dmSans = DM_Sans({
  subsets: ["latin"],
});

// Optional: Configure Geist fonts if needed
/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}